# Generated by Django 3.1.7 on 2021-03-12 21:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشركه')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name=' الهاتف الارضى')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=11, region=None, verbose_name='موبايل')),
                ('document1', models.IntegerField(verbose_name='رقم السجل التجارى')),
                ('document2', models.IntegerField(verbose_name='الرقم الضريبى')),
                ('address1', models.CharField(max_length=200, verbose_name='العنوان1')),
                ('address2', models.CharField(max_length=200, verbose_name='العنوان2')),
            ],
        ),
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='موبايل')),
                ('countBuyMony', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='مجموع المبالع المشترى من المورد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importers', to='comp.company', verbose_name='الشركه')),
            ],
        ),
    ]
