# Generated by Django 3.1.7 on 2021-03-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_auto_20210312_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importer',
            name='countBuyMony',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مجموع المبالع المشترى من المورد'),
        ),
    ]
