# Generated by Django 3.1.7 on 2021-03-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0003_auto_20210312_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAr', models.CharField(max_length=100, verbose_name='اسم الصنف بالعربيه')),
                ('nameEn', models.CharField(max_length=100, verbose_name='اسم الصنف بالانجليزيه')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='السعر')),
                ('date', models.DateTimeField(verbose_name='تاريخ الانتاج')),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='comp.importer')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cstName', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('taxNumber', models.PositiveIntegerField(verbose_name='الرقم الضريبى')),
                ('priceDate', models.DateTimeField(verbose_name='تاريخ التسعيره')),
                ('countty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكميه')),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='سعر الوحده')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الاجمالى')),
                ('price', models.CharField(max_length=50, verbose_name='مبلغ التسعيره')),
                ('discount', models.FloatField(verbose_name='الخصم')),
                ('afterDiscount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='بعد الخصم')),
                ('finalPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المجموع النهائى')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='comp.category', verbose_name='اسم الصنف')),
            ],
        ),
    ]
