# Generated by Django 3.1.7 on 2021-03-13 20:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0004_category_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.PositiveIntegerField(default=0, verbose_name='رقم العميل')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='رقم الهاتف')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مجموع المبالغ المدفوعه')),
                ('remaining_amounts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مجموع المبالغ المتبقيه')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='category_number',
            field=models.PositiveIntegerField(default=0, verbose_name='رقم الصنف'),
        ),
        migrations.AddField(
            model_name='importer',
            name='importer_number',
            field=models.PositiveIntegerField(default=0, verbose_name='رقم المورد'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField(default=0, verbose_name='رقم الفاتورة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم العميل')),
                ('taxNumber', models.PositiveIntegerField(verbose_name='الرقم الضريبى')),
                ('priceDate', models.DateTimeField(verbose_name='تاريخ الفاتورة')),
                ('countty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكميه')),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='سعر الوحده')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الاجمالى')),
                ('price', models.CharField(max_length=50, verbose_name='مبلغ الفاتورة')),
                ('discount', models.FloatField(verbose_name='الخصم')),
                ('afterDiscount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ بعد الخصم')),
                ('finalPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المجموع النهائى')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='comp.category', verbose_name='اسم الصنف')),
            ],
        ),
    ]
